// $(document).ready(function(){
//   $("#about-me-row").mouseenter(function(){
//     $("about-me-link").addClass("moused");
//   });
//   $("#about-me-row").mouseout(function(){
//     $("about-me-link").removeClass("moused");
//   });
//   $("#skills-row").mouseenter(function(){
//     $("skills-link").addClass("moused");
//   });
//   $("#skills-row").mouseout(function(){
//     $("skills-link").removeClass("moused");
//   });
//   $("#projects-row").mouseenter(function
//     $("projects-link").addClass("moused");
//   });
//   $("#projects-row").mouseout(function(){
//     $("projects-link").removeClass("moused");
//   });
//   $("#education-row").mouseenter(function(){
//     $("education-link").removeClass("moused");
//   });
//   $("#education-row").mouseout(function(){
//     $("education-link").removeClass("moused");
//   });
//   $("#work-row").mouseenter(function(){
//     $("work-link").removeClass("moused");
//   });
//   $("#work-row").mouseout(function(){
//     $("work-link").removeClass("moused");
//   });
//   $("#contact-row").mouseenter(function(){
//     $("contact-link").removeClass("moused");
//   });
//   $("#contact-row").mouseout(function(){
//     $("contact-link").removeClass("moused");
//   });
// });
